'use client';

import { useEffect, useRef } from 'react';
import { ArrowDown, ArrowUpRight, CodeXml, Download, Mail, MoveUpRight } from 'lucide-react';

const technologies = ['Python', 'Django', 'Java', 'JavaScript', 'HTML & CSS', 'SQL', 'Git'];
const skillGroups = [
  {number:'01',title:'Backend',detail:'Lógica, datos y aplicaciones web.',tools:['Python','Django','Java']},
  {number:'02',title:'Frontend',detail:'Interfaces claras que se adaptan a cada pantalla.',tools:['JavaScript','HTML','CSS']},
  {number:'03',title:'Bases de datos',detail:'Modelado y consultas para organizar la información.',tools:['SQL','MySQL']},
  {number:'04',title:'Flujo de trabajo',detail:'Control de versiones y desarrollo asistido por IA.',tools:['Git','GitHub','Codex']},
];

function TournamentDiagram(){return <div className="tournament" aria-label="Esquema del flujo de un torneo en PadelBracket"><div className="tournament-top"><span>PADEL<span>BRACKET</span></span><span className="diagram-label">FLUJO DEL TORNEO</span></div><div className="tournament-title">Del primer partido<br/>a la gran final<span>.</span></div><div className="bracket"><div className="round"><span>SEMIFINALES</span><div className="match"><p>Pareja A <b>↗</b></p><p>Pareja B</p></div><div className="match"><p>Pareja C <b>↗</b></p><p>Pareja D</p></div></div><div className="connector" aria-hidden="true"/><div className="round final"><span>FINAL</span><div className="match"><p>Pareja A</p><p>Pareja C</p></div></div></div><div className="diagram-footer"><span>Inscripciones</span><span>Eliminatorias</span><span>Resultados</span></div></div>}

export default function Home(){
  const portraitRef = useRef<HTMLDivElement>(null);
  useEffect(()=>{
    if(window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;
    const observer = new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target)}}),{threshold:0.12});
    document.querySelectorAll('[data-reveal]').forEach(el=>observer.observe(el));
    return ()=>observer.disconnect();
  },[]);
  return <main>
    <a className="skip-link" href="#proyectos">Saltar a los proyectos</a>
    <header className="nav"><a className="brand" href="#inicio" aria-label="Rafael Deusto, inicio">rd<span>.</span></a><nav aria-label="Navegación principal"><a href="#proyectos">Proyectos</a><a href="#sobre-mi">Sobre mí</a><a href="#contacto">Hablemos <ArrowUpRight size={16}/></a></nav></header>
    <section className="hero" id="inicio">
      <div className="hero-top"><span>DESARROLLADOR DE SOFTWARE JUNIOR</span><span>JEREZ, ESPAÑA ↗</span></div>
      <h1>RAFAEL <span>DEUSTO</span></h1>
      <div className="hero-bottom">
        <div className="intro"><span className="eyebrow">CURIOSIDAD. CÓDIGO. CONSTANCIA.</span><p>De una idea<br/>a algo que funciona.</p><div className="intro-copy">Desarrollo aplicaciones web con Python, Java y JavaScript. Aprendo construyendo y busco mi primera oportunidad en un equipo de desarrollo.</div><a className="pill light" href="#proyectos">Explora mis proyectos <ArrowDown size={18}/></a></div>
        <div className="portrait" ref={portraitRef} onPointerMove={event=>{if(event.pointerType==='mouse'&&!window.matchMedia('(prefers-reduced-motion: reduce)').matches){const r=event.currentTarget.getBoundingClientRect();event.currentTarget.style.setProperty('--px',`${((event.clientX-r.left)/r.width-.5)*10}px`);event.currentTarget.style.setProperty('--py',`${((event.clientY-r.top)/r.height-.5)*10}px`)}}} onPointerLeave={()=>{portraitRef.current?.style.setProperty('--px','0px');portraitRef.current?.style.setProperty('--py','0px')}}><img src={`${import.meta.env.BASE_URL}assets/rafael.png`} alt="Rafael Deusto Espinosa" width="1263" height="1600" fetchPriority="high"/><span className="portrait-caption">RAFAEL DEUSTO ESPINOSA <span>↗</span></span></div>
        <div className="hero-note"><span className="asterisk" aria-hidden="true">✳</span><p>Un perfil junior.<br/>Muchas ganas<br/>de aportar.</p><a href="https://github.com/faliideusto" target="_blank" rel="noreferrer"><CodeXml size={18}/> GitHub <ArrowUpRight size={16}/></a></div>
      </div>
    </section>
    <div className="tech-ribbon" aria-label="Python, Django, Java, JavaScript, HTML y CSS, SQL, Git"><div className="tech-track" aria-hidden="true">{[0,1].map(copy=><div className="tech-set" key={copy}>{technologies.map(tech=><span key={tech}>{tech}<i>✳</i></span>)}</div>)}</div></div>
    <section className="projects" id="proyectos">
      <div className="section-head" data-reveal><div><span className="eyebrow">01 / PROYECTOS SELECCIONADOS</span><p className="section-aside">Dos contextos distintos.<br/>La misma forma de aprender: hacer.</p></div><h2>Código que<br/><em>toma forma.</em></h2></div>
      <article className="project" data-reveal><div className="project-info"><div className="project-index">01 <span>PROYECTO FINAL DE DAW</span></div><h3>PadelBracket<span>↗</span></h3><p>Una aplicación para organizar torneos de pádel de principio a fin: parejas, inscripciones, cruces y resultados en un mismo lugar.</p><div className="contribution"><span>MI TRABAJO</span><p>Desarrollo del proyecto: usuarios y roles de jugador y organizador, gestión de inscripciones y generación de eliminatorias con avance de ganadores.</p></div><div className="tags">{['Python','Django','MySQL','JavaScript'].map(t=><span key={t}>{t}</span>)}</div><a className="project-link" href="https://github.com/faliideusto/PadelBracket" target="_blank" rel="noreferrer">Explorar el código <ArrowUpRight size={20}/></a></div><TournamentDiagram/></article>
      <article className="project tesis-project" data-reveal><div className="project-info"><div className="project-index">02 <span>COLABORACIÓN UNIVERSITARIA</span></div><h3>Tesis<span>↗</span></h3><p>Un juego de cartas multijugador que lleva la investigación académica a la mesa. Desarrollado en colaboración con un profesor universitario.</p><div className="contribution"><span>MI CONTRIBUCIÓN</span><p>A partir de una estructura inicial compartida, desarrollo del flujo de partida, acciones y roles, experiencia web y funcionalidades multijugador.</p></div><div className="tags">{['Java','JavaScript','HTML','CSS'].map(t=><span key={t}>{t}</span>)}</div><a className="project-link" href="https://github.com/Alvarogm15/Ciudadelas" target="_blank" rel="noreferrer">Explorar el código <ArrowUpRight size={20}/></a></div><figure className="tesis-visual"><img src={`${import.meta.env.BASE_URL}assets/tesis.png`} alt="Captura de una partida de Tesis: mesa de juego, personajes y cartas de investigación" width="1600" height="900" loading="lazy"/><figcaption><span>Una partida de Tesis</span><span>EN DESARROLLO</span></figcaption></figure></article>
    </section>
    <section className="about" id="sobre-mi"><div className="about-head" data-reveal><span className="eyebrow">02 / UN POCO SOBRE MÍ</span><span className="asterisk" aria-hidden="true">✳</span></div><h2 data-reveal>Aprender haciendo.<br/><em>Crecer en equipo.</em></h2><div className="about-body" data-reveal><span className="about-label">MÁS ALLÁ DEL CÓDIGO</span><div><p>Soy Rafael, desarrollador junior de Jerez. Me gusta entender cómo funcionan las cosas y convertir ese aprendizaje en aplicaciones que se puedan usar.</p><p>He completado la formación académica de Desarrollo de Aplicaciones Web y estoy pendiente de las prácticas. Busco un equipo donde aportar, recibir feedback y seguir aprendiendo con proyectos reales.</p><p>Uso la IA como apoyo durante el desarrollo: para explorar soluciones, revisar ideas y aprender tecnologías. Me interesa comprender lo que construyo y comprobar que funciona.</p><a className="text-link" href={`${import.meta.env.BASE_URL}assets/Rafael-Deusto-CV.pdf`} download>Descargar mi CV <Download size={18}/></a></div></div><div className="experience-note" data-reveal><span>DUBLÍN · 2021</span><p>Ocho meses en Starbucks del aeropuerto de Dublín: cuatro como barista y cuatro como responsable de equipo. Una experiencia trabajando íntegramente en inglés que me enseñó a comunicarme, coordinarme y responder bajo presión.</p></div></section>
    <section className="skills" id="tecnologias"><div className="section-head" data-reveal><span className="eyebrow">03 / HERRAMIENTAS Y APRENDIZAJE</span><h2>Mi caja<br/>de herramientas.</h2></div><div className="skill-list">{skillGroups.map(group=><div className="skill-row" key={group.number} data-reveal><span className="skill-number">{group.number}</span><div><h3>{group.title}</h3><p>{group.detail}</p></div><div className="tags">{group.tools.map(tool=><span key={tool}>{tool}</span>)}</div><MoveUpRight className="skill-arrow" size={26}/></div>)}</div><div className="learning-grid"><div data-reveal><span className="eyebrow">FORMACIÓN</span><h3>Desarrollo de<br/>Aplicaciones Web</h3><p className="learning-date">2024–2026</p><p>IES Romero Vargas · 2024–2025<br/>ILERNA · 2025–2026</p><p className="status">Formación académica completada · prácticas pendientes</p></div><div data-reveal><span className="eyebrow">APRENDIZAJE CONTINUO</span><h3>La curiosidad<br/>sigue abierta.</h3><p>Cursos de Java y Python · 2022–2024</p><a className="course-link" href="https://www.youtube.com/watch?v=XcUOWCXP5u8" target="_blank" rel="noreferrer">Curso de Codex y agentes de IA <ArrowUpRight size={16}/></a><p className="course-meta">Formación online · Benjamín Cordero</p><div className="languages"><span>IDIOMAS</span><p>Español: nativo · Inglés: B1 certificado</p><p>Experiencia profesional trabajando íntegramente en inglés en Dublín.</p></div></div></div></section>
    <section className="contact" id="contacto"><div className="contact-top" data-reveal><span className="eyebrow">04 / SIGUIENTE PASO</span><span>PRIMER EMPLEO · PRÁCTICAS</span></div><h2 data-reveal>¿Construimos<br/><em>algo juntos?</em><ArrowUpRight aria-hidden="true"/></h2><div className="contact-bottom" data-reveal><p>Estoy buscando mi primera oportunidad<br/>en desarrollo de software.<br/><span>Me encantará conocer a tu equipo.</span></p><a className="pill contact-pill" href="mailto:radeusto@gmail.com"><Mail size={21}/> Hablemos <ArrowUpRight size={22}/></a></div><div className="contact-links"><a href="mailto:radeusto@gmail.com">radeusto@gmail.com</a><a href="https://github.com/faliideusto" target="_blank" rel="noreferrer">GitHub <ArrowUpRight size={16}/></a><a href={`${import.meta.env.BASE_URL}assets/Rafael-Deusto-CV.pdf`} download>Descargar CV <Download size={16}/></a></div></section>
    <footer><a className="brand" href="#inicio" aria-label="Volver al inicio">rd<span>.</span></a><span>© 2026 Rafael Deusto Espinosa</span><a href="#inicio">Volver arriba ↑</a></footer>
  </main>
}

